// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	model "github.com/sentrionic/mirage/model"
	mock "github.com/stretchr/testify/mock"
)

// PostRepository is an autogenerated mock type for the PostRepository type
type PostRepository struct {
	mock.Mock
}

// AddLike provides a mock function with given fields: post, uid
func (_m *PostRepository) AddLike(post *model.Post, uid string) error {
	ret := _m.Called(post, uid)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Post, string) error); ok {
		r0 = rf(post, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddRetweet provides a mock function with given fields: post, uid
func (_m *PostRepository) AddRetweet(post *model.Post, uid string) error {
	ret := _m.Called(post, uid)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Post, string) error); ok {
		r0 = rf(post, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: post
func (_m *PostRepository) Create(post *model.Post) (*model.Post, error) {
	ret := _m.Called(post)

	var r0 *model.Post
	if rf, ok := ret.Get(0).(func(*model.Post) *model.Post); ok {
		r0 = rf(post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Post) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: post
func (_m *PostRepository) Delete(post *model.Post) error {
	ret := _m.Called(post)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Post) error); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Feed provides a mock function with given fields: userId, cursor
func (_m *PostRepository) Feed(userId string, cursor string) (*[]model.Post, error) {
	ret := _m.Called(userId, cursor)

	var r0 *[]model.Post
	if rf, ok := ret.Get(0).(func(string, string) *[]model.Post); ok {
		r0 = rf(userId, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userId, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *PostRepository) FindByID(id string) (*model.Post, error) {
	ret := _m.Called(id)

	var r0 *model.Post
	if rf, ok := ret.Get(0).(func(string) *model.Post); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPostsForHashtag provides a mock function with given fields: tag, cursor
func (_m *PostRepository) GetPostsForHashtag(tag string, cursor string) (*[]model.Post, error) {
	ret := _m.Called(tag, cursor)

	var r0 *[]model.Post
	if rf, ok := ret.Get(0).(func(string, string) *[]model.Post); ok {
		r0 = rf(tag, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(tag, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Likes provides a mock function with given fields: id, cursor
func (_m *PostRepository) Likes(id string, cursor string) (*[]model.Post, error) {
	ret := _m.Called(id, cursor)

	var r0 *[]model.Post
	if rf, ok := ret.Get(0).(func(string, string) *[]model.Post); ok {
		r0 = rf(id, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: id, cursor
func (_m *PostRepository) List(id string, cursor string) (*[]model.Post, error) {
	ret := _m.Called(id, cursor)

	var r0 *[]model.Post
	if rf, ok := ret.Get(0).(func(string, string) *[]model.Post); ok {
		r0 = rf(id, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Media provides a mock function with given fields: id, cursor
func (_m *PostRepository) Media(id string, cursor string) (*[]model.Post, error) {
	ret := _m.Called(id, cursor)

	var r0 *[]model.Post
	if rf, ok := ret.Get(0).(func(string, string) *[]model.Post); ok {
		r0 = rf(id, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveLike provides a mock function with given fields: post, uid
func (_m *PostRepository) RemoveLike(post *model.Post, uid string) error {
	ret := _m.Called(post, uid)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Post, string) error); ok {
		r0 = rf(post, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveRetweet provides a mock function with given fields: post, uid
func (_m *PostRepository) RemoveRetweet(post *model.Post, uid string) error {
	ret := _m.Called(post, uid)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Post, string) error); ok {
		r0 = rf(post, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
